"""add audit log, agent execution, tasks, appointments, calendar connections, notifications

Revision ID: 30a260e1a343
Revises: b4e0f2427062
Create Date: 2026-09-08 23:34:41.450295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30a260e1a343'
down_revision: Union[str, Sequence[str], None] = 'b4e0f2427062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_version', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('human_action', sa.String(), nullable=True),
    sa.Column('human_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_executions_contact_id', 'agent_executions', ['contact_id'], unique=False)
    op.create_index('ix_agent_executions_org_agent', 'agent_executions', ['organization_id', 'agent_name'], unique=False)
    op.create_index('ix_agent_executions_org_created_at', 'agent_executions', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_agent_executions_organization_id', 'agent_executions', ['organization_id'], unique=False)
    op.create_table('appointments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('appointment_type', sa.String(), nullable=False),
    sa.Column('external_calendar_event_id', sa.String(), nullable=True),
    sa.Column('external_calendar_provider', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_at <= end_at', name='ck_appointments_start_before_end'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_assigned_to_user_id', 'appointments', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_appointments_contact_id', 'appointments', ['contact_id'], unique=False)
    op.create_index('ix_appointments_org_start_at', 'appointments', ['organization_id', 'start_at'], unique=False)
    op.create_index('ix_appointments_organization_id', 'appointments', ['organization_id'], unique=False)
    op.create_index('ix_appointments_property_id', 'appointments', ['property_id'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_org_created_at', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_org_entity', 'audit_logs', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_organization_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_table('calendar_connections',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_calendar_connections_user_provider')
    )
    op.create_index('ix_calendar_connections_organization_id', 'calendar_connections', ['organization_id'], unique=False)
    op.create_index('ix_calendar_connections_user_id', 'calendar_connections', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_organization_id', 'notifications', ['organization_id'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('tasks',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('buyer_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('property_interest_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_interest_id'], ['property_interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assigned_to_user_id', 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_tasks_buyer_requirement_id', 'tasks', ['buyer_requirement_id'], unique=False)
    op.create_index('ix_tasks_contact_id', 'tasks', ['contact_id'], unique=False)
    op.create_index('ix_tasks_org_status_due', 'tasks', ['organization_id', 'status', 'due_at'], unique=False)
    op.create_index('ix_tasks_organization_id', 'tasks', ['organization_id'], unique=False)
    op.create_index('ix_tasks_property_id', 'tasks', ['property_id'], unique=False)
    op.create_index('ix_tasks_property_interest_id', 'tasks', ['property_interest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_property_interest_id', table_name='tasks')
    op.drop_index('ix_tasks_property_id', table_name='tasks')
    op.drop_index('ix_tasks_organization_id', table_name='tasks')
    op.drop_index('ix_tasks_org_status_due', table_name='tasks')
    op.drop_index('ix_tasks_contact_id', table_name='tasks')
    op.drop_index('ix_tasks_buyer_requirement_id', table_name='tasks')
    op.drop_index('ix_tasks_assigned_to_user_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_notifications_user_read_at', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_organization_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_calendar_connections_user_id', table_name='calendar_connections')
    op.drop_index('ix_calendar_connections_organization_id', table_name='calendar_connections')
    op.drop_table('calendar_connections')
    op.drop_index('ix_audit_logs_organization_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_property_id', table_name='appointments')
    op.drop_index('ix_appointments_organization_id', table_name='appointments')
    op.drop_index('ix_appointments_org_start_at', table_name='appointments')
    op.drop_index('ix_appointments_contact_id', table_name='appointments')
    op.drop_index('ix_appointments_assigned_to_user_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_agent_executions_organization_id', table_name='agent_executions')
    op.drop_index('ix_agent_executions_org_created_at', table_name='agent_executions')
    op.drop_index('ix_agent_executions_org_agent', table_name='agent_executions')
    op.drop_index('ix_agent_executions_contact_id', table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
