"""initial schema

Revision ID: 3ae798c63c36
Revises: 
Create Date: 2026-09-08 13:17:01.483573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.seed_data import FEATURE_SEEDS, ROLE_SEEDS


# revision identifiers, used by Alembic.
revision: str = '3ae798c63c36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Lightweight ad-hoc table refs (not the ORM models) for the seed inserts
# below — the standard Alembic pattern, so this migration keeps working
# unchanged even if the models it originally matched are edited later.
_roles_table = sa.table("roles", sa.column("key", sa.String), sa.column("label", sa.String))
_features_table = sa.table("features", sa.column("key", sa.String), sa.column("label", sa.String))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('contacts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='ck_contacts_email_or_phone'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_org_email', 'contacts', ['organization_id', 'email'], unique=False)
    op.create_index('ix_contacts_org_phone', 'contacts', ['organization_id', 'phone'], unique=False)
    op.create_index('ix_contacts_organization_id', 'contacts', ['organization_id'], unique=False)
    op.create_table('properties',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('address_line', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('construction_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('land_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bedrooms', sa.SmallInteger(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('parking_spaces', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_properties_org_status_city_type', 'properties', ['organization_id', 'status', 'city', 'property_type'], unique=False)
    op.create_index('ix_properties_organization_id', 'properties', ['organization_id'], unique=False)
    op.create_index('ix_properties_price', 'properties', ['price'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_table('buyer_requirements',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('bedrooms_min', sa.SmallInteger(), nullable=True),
    sa.Column('bedrooms_max', sa.SmallInteger(), nullable=True),
    sa.Column('bathrooms_min', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('bathrooms_max', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('construction_m2_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('construction_m2_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('land_m2_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('land_m2_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('parking_spaces_min', sa.SmallInteger(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.Column('financing_type', sa.String(), nullable=True),
    sa.Column('preapproval_status', sa.String(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bathrooms_min IS NULL OR bathrooms_max IS NULL OR bathrooms_min <= bathrooms_max', name='ck_buyer_requirements_bathrooms_range'),
    sa.CheckConstraint('bedrooms_min IS NULL OR bedrooms_max IS NULL OR bedrooms_min <= bedrooms_max', name='ck_buyer_requirements_bedrooms_range'),
    sa.CheckConstraint('budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max', name='ck_buyer_requirements_budget_range'),
    sa.CheckConstraint('construction_m2_min IS NULL OR construction_m2_max IS NULL OR construction_m2_min <= construction_m2_max', name='ck_buyer_requirements_construction_m2_range'),
    sa.CheckConstraint('land_m2_min IS NULL OR land_m2_max IS NULL OR land_m2_min <= land_m2_max', name='ck_buyer_requirements_land_m2_range'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buyer_requirements_budget_range', 'buyer_requirements', ['budget_min', 'budget_max'], unique=False)
    op.create_index('ix_buyer_requirements_contact_id', 'buyer_requirements', ['contact_id'], unique=False)
    op.create_index('ix_buyer_requirements_organization_id', 'buyer_requirements', ['organization_id'], unique=False)
    op.create_index('ix_buyer_requirements_property_type', 'buyer_requirements', ['property_type'], unique=False)
    op.create_index('ix_buyer_requirements_status', 'buyer_requirements', ['status'], unique=False)
    op.create_table('contact_roles',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('role_key', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_key'], ['roles.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'role_key', name='uq_contact_roles_contact_role')
    )
    op.create_table('property_features',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feature_key'], ['features.key'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'feature_key', name='uq_property_features_property_feature')
    )
    op.create_table('property_interests',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_property_interests_contact_id', 'property_interests', ['contact_id'], unique=False)
    op.create_index('ix_property_interests_contact_property', 'property_interests', ['contact_id', 'property_id'], unique=False)
    op.create_index('ix_property_interests_organization_id', 'property_interests', ['organization_id'], unique=False)
    op.create_index('ix_property_interests_property_id', 'property_interests', ['property_id'], unique=False)
    op.create_index('ix_property_interests_status', 'property_interests', ['status'], unique=False)
    op.create_table('buyer_requirement_features',
    sa.Column('buyer_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_key'], ['features.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_requirement_id', 'feature_key', name='uq_buyer_requirement_features_requirement_feature')
    )
    op.create_table('buyer_requirement_locations',
    sa.Column('buyer_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('city IS NOT NULL OR neighborhood IS NOT NULL', name='ck_buyer_requirement_locations_city_or_neighborhood'),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buyer_requirement_locations_city_neighborhood', 'buyer_requirement_locations', ['city', 'neighborhood'], unique=False)
    op.create_index('ix_buyer_requirement_locations_requirement_id', 'buyer_requirement_locations', ['buyer_requirement_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the roles/features catalogs — contact_roles, property_features,
    # and buyer_requirement_features all foreign-key into these, so nothing
    # can reference a role/feature until it exists here.
    op.bulk_insert(_roles_table, ROLE_SEEDS)
    op.bulk_insert(_features_table, FEATURE_SEEDS)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buyer_requirement_locations_requirement_id', table_name='buyer_requirement_locations')
    op.drop_index('ix_buyer_requirement_locations_city_neighborhood', table_name='buyer_requirement_locations')
    op.drop_table('buyer_requirement_locations')
    op.drop_table('buyer_requirement_features')
    op.drop_index('ix_property_interests_status', table_name='property_interests')
    op.drop_index('ix_property_interests_property_id', table_name='property_interests')
    op.drop_index('ix_property_interests_organization_id', table_name='property_interests')
    op.drop_index('ix_property_interests_contact_property', table_name='property_interests')
    op.drop_index('ix_property_interests_contact_id', table_name='property_interests')
    op.drop_table('property_interests')
    op.drop_table('property_features')
    op.drop_table('contact_roles')
    op.drop_index('ix_buyer_requirements_status', table_name='buyer_requirements')
    op.drop_index('ix_buyer_requirements_property_type', table_name='buyer_requirements')
    op.drop_index('ix_buyer_requirements_organization_id', table_name='buyer_requirements')
    op.drop_index('ix_buyer_requirements_contact_id', table_name='buyer_requirements')
    op.drop_index('ix_buyer_requirements_budget_range', table_name='buyer_requirements')
    op.drop_table('buyer_requirements')
    op.drop_index('ix_users_organization_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_properties_price', table_name='properties')
    op.drop_index('ix_properties_organization_id', table_name='properties')
    op.drop_index('ix_properties_org_status_city_type', table_name='properties')
    op.drop_table('properties')
    op.drop_index('ix_contacts_organization_id', table_name='contacts')
    op.drop_index('ix_contacts_org_phone', table_name='contacts')
    op.drop_index('ix_contacts_org_email', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('features')
    # ### end Alembic commands ###
