"""add property ownership and collaboration fields

Revision ID: 932767fd7b15
Revises: bc7b6fe4029f
Create Date: 2026-09-10 17:54:38.284137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932767fd7b15'
down_revision: Union[str, Sequence[str], None] = 'bc7b6fe4029f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('ownership_type', sa.String(), server_default='own', nullable=False))
    op.add_column('properties', sa.Column('external_source', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('external_advisor_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('external_advisor_contact', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('collaboration_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'collaboration_status')
    op.drop_column('properties', 'external_advisor_contact')
    op.drop_column('properties', 'external_advisor_name')
    op.drop_column('properties', 'external_source')
    op.drop_column('properties', 'ownership_type')
    # ### end Alembic commands ###
