"""add feature catalog fields and location uniqueness

Revision ID: b4e0f2427062
Revises: cdb1324b4347
Create Date: 2026-09-08 22:42:31.226518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e0f2427062'
down_revision: Union[str, Sequence[str], None] = 'cdb1324b4347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Category backfill for the 11 rows bulk_inserted by the initial_schema migration
# (3ae798c63c36) — those rows predate `category` and are never re-run by the
# idempotent demo seed script (app/core/seed_data.py), so without this they'd be
# left with category=NULL forever. Mirrors app/core/seed_data.py's FEATURE_SEEDS,
# which is updated in the same change for any future fresh install.
FEATURE_CATEGORY_BACKFILL = {
    "garden": "exterior",
    "pool": "exterior",
    "terrace": "exterior",
    "balcony": "exterior",
    "home_office": "interior",
    "maid_quarters": "interior",
    "laundry_room": "interior",
    "elevator": "amenity",
    "security": "security",
    "gated_community": "security",
    "pet_friendly": "other",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_buyer_requirement_locations_requirement_place', 'buyer_requirement_locations', ['buyer_requirement_id', sa.literal_column("COALESCE(city, '')"), sa.literal_column("COALESCE(state, '')"), sa.literal_column("COALESCE(neighborhood, '')")], unique=True)
    op.add_column('features', sa.Column('category', sa.String(), nullable=True))
    op.add_column('features', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('features', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('features', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

    features = sa.table("features", sa.column("key", sa.String), sa.column("category", sa.String))
    for key, category in FEATURE_CATEGORY_BACKFILL.items():
        op.execute(features.update().where(features.c.key == key).values(category=category))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'created_at')
    op.drop_column('features', 'updated_at')
    op.drop_column('features', 'is_active')
    op.drop_column('features', 'category')
    op.drop_index('uq_buyer_requirement_locations_requirement_place', table_name='buyer_requirement_locations')
    # ### end Alembic commands ###
