"""add opportunities and link to activities tasks appointments

Revision ID: bc7b6fe4029f
Revises: 30a260e1a343
Create Date: 2026-09-09 00:04:47.526118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7b6fe4029f'
down_revision: Union[str, Sequence[str], None] = '30a260e1a343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('buyer_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('opportunity_type', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('probability', sa.SmallInteger(), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expected_value IS NULL OR expected_value >= 0', name='ck_opportunities_expected_value_nonnegative'),
    sa.CheckConstraint('probability IS NULL OR (probability >= 0 AND probability <= 100)', name='ck_opportunities_probability_range'),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_buyer_requirement_id', 'opportunities', ['buyer_requirement_id'], unique=False)
    op.create_index('ix_opportunities_contact_id', 'opportunities', ['contact_id'], unique=False)
    op.create_index('ix_opportunities_expected_close_date', 'opportunities', ['expected_close_date'], unique=False)
    op.create_index('ix_opportunities_org_owner', 'opportunities', ['organization_id', 'owner_user_id'], unique=False)
    op.create_index('ix_opportunities_org_type_stage', 'opportunities', ['organization_id', 'opportunity_type', 'stage'], unique=False)
    op.create_index('ix_opportunities_organization_id', 'opportunities', ['organization_id'], unique=False)
    op.create_index('ix_opportunities_owner_user_id', 'opportunities', ['owner_user_id'], unique=False)
    op.create_index('ix_opportunities_property_id', 'opportunities', ['property_id'], unique=False)
    op.add_column('activities', sa.Column('opportunity_id', sa.Uuid(), nullable=True))
    op.create_index('ix_activities_opportunity_id', 'activities', ['opportunity_id'], unique=False)
    op.create_foreign_key(
        'fk_activities_opportunity_id', 'activities', 'opportunities', ['opportunity_id'], ['id'], ondelete='SET NULL'
    )
    op.add_column('appointments', sa.Column('opportunity_id', sa.Uuid(), nullable=True))
    op.create_index('ix_appointments_opportunity_id', 'appointments', ['opportunity_id'], unique=False)
    op.create_foreign_key(
        'fk_appointments_opportunity_id', 'appointments', 'opportunities', ['opportunity_id'], ['id'], ondelete='SET NULL'
    )
    op.add_column('tasks', sa.Column('opportunity_id', sa.Uuid(), nullable=True))
    op.create_index('ix_tasks_opportunity_id', 'tasks', ['opportunity_id'], unique=False)
    op.create_foreign_key(
        'fk_tasks_opportunity_id', 'tasks', 'opportunities', ['opportunity_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_opportunity_id', 'tasks', type_='foreignkey')
    op.drop_index('ix_tasks_opportunity_id', table_name='tasks')
    op.drop_column('tasks', 'opportunity_id')
    op.drop_constraint('fk_appointments_opportunity_id', 'appointments', type_='foreignkey')
    op.drop_index('ix_appointments_opportunity_id', table_name='appointments')
    op.drop_column('appointments', 'opportunity_id')
    op.drop_constraint('fk_activities_opportunity_id', 'activities', type_='foreignkey')
    op.drop_index('ix_activities_opportunity_id', table_name='activities')
    op.drop_column('activities', 'opportunity_id')
    op.drop_index('ix_opportunities_property_id', table_name='opportunities')
    op.drop_index('ix_opportunities_owner_user_id', table_name='opportunities')
    op.drop_index('ix_opportunities_organization_id', table_name='opportunities')
    op.drop_index('ix_opportunities_org_type_stage', table_name='opportunities')
    op.drop_index('ix_opportunities_org_owner', table_name='opportunities')
    op.drop_index('ix_opportunities_expected_close_date', table_name='opportunities')
    op.drop_index('ix_opportunities_contact_id', table_name='opportunities')
    op.drop_index('ix_opportunities_buyer_requirement_id', table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
