"""add activities table

Revision ID: cdb1324b4347
Revises: 3ae798c63c36
Create Date: 2026-09-08 14:26:13.145559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb1324b4347'
down_revision: Union[str, Sequence[str], None] = '3ae798c63c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_activity_type', 'activities', ['activity_type'], unique=False)
    op.create_index('ix_activities_contact_id', 'activities', ['contact_id'], unique=False)
    op.create_index('ix_activities_contact_occurred', 'activities', ['contact_id', 'occurred_at'], unique=False)
    op.create_index('ix_activities_occurred_at', 'activities', ['occurred_at'], unique=False)
    op.create_index('ix_activities_organization_id', 'activities', ['organization_id'], unique=False)
    op.create_index('ix_activities_property_id', 'activities', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_property_id', table_name='activities')
    op.drop_index('ix_activities_organization_id', table_name='activities')
    op.drop_index('ix_activities_occurred_at', table_name='activities')
    op.drop_index('ix_activities_contact_occurred', table_name='activities')
    op.drop_index('ix_activities_contact_id', table_name='activities')
    op.drop_index('ix_activities_activity_type', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
